import os

env = Environment()

installDir = '/home/pi/public_html/piPad/ws'

env.ParseConfig('pkg-config --cflags --libs apr-1')
env.Append(CCFLAGS = ['-Wall', '-pthread'])
env.Append(CPPPATH = ['/usr/include/apache2','/home/pi/repos/apache-websocket'])

pipe = env.SharedLibrary(source=["mod_websocket_pipe.c"], 
                         SHLIBPREFIX="", 
                         SHLIBSUFFIX=".so")

repeater = env.SharedLibrary(source=["mod_websocket_repeater.c"], 
                         SHLIBPREFIX="", 
                         SHLIBSUFFIX=".so")

env.Install(installDir, [repeater])
env.Alias('install', [installDir])
